//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KZVLDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Players()
        {
            this.Groups = new HashSet<Groups>();
            this.Teams1 = new HashSet<Teams>();
        }
    
        public int PL_Id { get; set; }
        public Nullable<int> PL_Number { get; set; }
        public string PL_Name { get; set; }
        public Nullable<int> PL_Height { get; set; }
        public Nullable<int> PL_Role_Role_Id { get; set; }
        public Nullable<int> PL_Team_Teams_Id { get; set; }
        public Nullable<int> PL_CountOfBestPlayerMatch { get; set; }
        public string PL_Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Groups> Groups { get; set; }
        public virtual Role Role { get; set; }
        public virtual Teams Teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teams> Teams1 { get; set; }
    }
}
